name: superhero
description: An evolution on Heroes in Flutter, supporting Spring-based animations as well as cleaner route transitions.
version: 0.1.0


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  springster: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.1.1
  mocktail: ^1.0.3
