name: Version

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Version as prerelease'
        required: false
        default: false
        type: boolean

jobs:
  prepare-release:
    name: Prepare release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Ⓜ️ Set up Melos
        uses: bluefireteam/melos-action@be64ed744ff5651ee3e5355041cf2f1495eae87c
        with:
          run-versioning: ${{ inputs.prerelease == false }}
          run-versioning-prerelease: ${{ inputs.prerelease == true }}
          publish-dry-run: true
          create-pr: true
          git-email: github-actions[bot]@users.noreply.github.com
          git-name: github-actions[bot]